% Beautiful_gtaph

% figure('Renderer', 'painters', 'Position', [1.0000    1.0000  990.5000  642.5000])
hold on
% plot
% P1=plot(sum(Shaped,1));
% P2=plot(sum(Baseline,1));
% P3=plot(sum(Target,1));

% adjust lines
set(P(1)                          ,...
  'LineWidth'       , 2       ,...
  'LineStyle'       , '-'      ,...
  'Color'           , [0,0.65,0.65]       ,...
  'Marker'          ,'none');

set(P(2)                         ,...
  'LineWidth'       , 2      ,...
  'LineStyle'       , '-'      ,...
  'Color'           ,  [0,0.4,0.4]);

set(P(3)                          ,...
  'LineWidth'       , 2       ,...
  'LineStyle'       , '-'      ,...
  'Color'           ,  [0,0.8,0.8]       ,...
  'Marker'          ,'none');

set(P(4)                          ,...
  'LineWidth'       , 3       ,...
  'LineStyle'       , ':'      ,...
  'Color'           , [0.6,0.6,0.6]       ,...
  'Marker'          ,'none');


set(P(5)                          ,...
  'LineWidth'       , 2       ,...
  'LineStyle'       , '-'      ,...
  'Color'           ,  [0,0.7,0.7]       ,...
  'Marker'          ,'none');

set(P(6)                          ,...
  'LineWidth'       , 2       ,...
  'LineStyle'       , '-'      ,...
  'Color'           ,  [0,0.6,0.6]       ,...
  'Marker'          ,'none');

set(P(7)                          ,...
  'LineWidth'       , 2       ,...
  'LineStyle'       , '-'      ,...
  'Color'           ,  [0,0.5,0.5]       ,...
  'Marker'          ,'none');

set(P(8)                          ,...
  'LineWidth'       , 2       ,...
  'LineStyle'       , '-'      ,...
  'Color'           ,  [0,0,0]       ,...
  'Marker'          ,'o',...
  'MarkerSize'      ,6,     ...
  'MarkerFaceColor',[1,1,1]);

% legend and labels

Title  = title ('Goodness of fit, weighted combination of CV and NMBE');
XLabel = xlabel('Number of clusters (sample size %)');
YLabel = ylabel('GOF (%)' );

% Text   = text(10, 800, ...
%   sprintf('\\it{C = %0.1g \\pm %0.1g (CI)}', ...
%   c, cint(2)-c));

Legend = legend( ...
  [P(1),P(2),P(3),P(4),P(5),P(6),P(7),P(8)], ...
  '15m' , ...
  '30m',...
  '45m',...
  '1h',...
  '1h 15m',...
  '1h 30m',...
  '1h 45 m',...
  '2h'  );


% font and axes

set(gca, ...
  'FontSize'    ,20      ,...
  'FontName'    , 'Serif'       ,...
  'Box'         , 'on'     , ...
  'TickDir'     , 'in'     , ...
  'TickLength'  , [.01 .01] , ...
  'XMinorTick'  , 'off'      , ...
  'YMinorTick'  , 'off'      , ...
  'YGrid'       , 'on'      , ...
  'GridLineStyle','--'      ,...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'LineWidth'   , 1        ,...
  'XTick'       ,1:length(labelx),...
  'XTickLabel' ,  labelx,     ...
  'XTickLabelRotation', 45);

set( gca                       , ...
    'defaulttextinterpreter','latex');
set([Title, XLabel, YLabel], ...
    'FontName'   , 'Serif');
set([Legend, gca]             , ...
    'FontSize'   , 14           );
set([XLabel, YLabel]  , ...
    'FontSize'   , 20         );
set( Title                    , ...
    'FontSize'   , 22          , ...
    'FontWeight' , 'normal'      );


set(gcf, 'PaperPositionMode', 'auto');
% print -depsc2 finalPlot1.eps


% saveas(figure(1),[pwd '/subFolderName/myFig.fig']);







